# fly.toml app configuration file for kontrolplane/feed
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "fork-feed"
primary_region = "fra"

[build]

[env]
  HOST = "127.0.0.1"
  PORT = "8080"
  REQUIRE_TUNNEL = "true"
  DATABASE_DRIVER = "sqlite"
  DATABASE_PATH = "/data/feed.db"

[mounts]
  source = "feed_store"
  destination = "/data"

[[vm]]
  memory = "256mb"
  memory_mb = 256
  cpu_kind = "shared"  
  cpus = 1

