// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddFolderModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"scrim\" onclick=\"document.getElementById('modal').innerHTML=''\"><div class=\"modal\" onclick=\"event.stopPropagation()\"><div class=\"modal-head\"><span>[ new / folder ]</span> <span class=\"close\" onclick=\"document.getElementById('modal').innerHTML=''\">✕</span></div><div class=\"modal-body\"><h2>create a folder.</h2><div class=\"sub\">organise your feeds into groups.</div><form hx-post=\"/folders\" hx-target=\"#sidebar\" hx-swap=\"outerHTML\" hx-on::after-request=\"document.getElementById('modal').innerHTML=''\"><label>folder name</label> <input type=\"text\" name=\"name\" placeholder=\"e.g. tech, news, blogs\" required autofocus><div class=\"btns\"><button type=\"button\" class=\"ghost\" onclick=\"document.getElementById('modal').innerHTML=''\">cancel</button> <button type=\"submit\" class=\"primary\">create →</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
