// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>kontrolplane/feed - rss, without the noise</title><link rel=\"stylesheet\" href=\"/static/css/styles.css\"><link rel=\"icon\" href=\"/static/assets/favicon.ico\" type=\"image/x-icon\"><script>\n\t\t\t(function(){var t=localStorage.getItem('theme');if(t==='dark')document.documentElement.setAttribute('data-theme','dark');})();\n\t\t\tfunction setTheme(t){localStorage.setItem('theme',t);if(t==='dark'){document.documentElement.setAttribute('data-theme','dark')}else{document.documentElement.removeAttribute('data-theme')}document.querySelectorAll('#theme-opts button').forEach(function(b){b.classList.remove('on')});var el=document.getElementById('theme-'+t);if(el)el.classList.add('on');}\n\t\t\tfunction togglePane(pane){\n\t\t\t\tvar app=document.querySelector('.app');\n\t\t\t\tvar cls=pane+'-collapsed';\n\t\t\t\tapp.classList.toggle(cls);\n\t\t\t\tlocalStorage.setItem(pane+'-collapsed',app.classList.contains(cls)?'1':'0');\n\t\t\t}\n\t\t</script></head><body><div class=\"app\"><header class=\"topbar\"><div class=\"brand\"><img src=\"/static/assets/logo.png\" alt=\"\" class=\"brand-logo\"> kontrolplane/feed</div><div class=\"search\"><span class=\"prompt\">/</span> <input type=\"search\" name=\"q\" placeholder=\"search items, authors, abstracts…\" hx-get=\"/search\" hx-trigger=\"keyup changed delay:200ms, search\" hx-target=\"#main\" hx-swap=\"outerHTML\" hx-indicator=\"#sync-indicator\"> <kbd>/</kbd></div><div class=\"tools\"><button class=\"btn\" hx-get=\"/feeds/new\" hx-target=\"#modal\" hx-swap=\"innerHTML\">＋ add feed</button> <button class=\"btn\" hx-get=\"/partials/list\" hx-target=\"#main\" hx-swap=\"outerHTML\" hx-indicator=\"#sync-indicator\"><span class=\"dot\"></span> sync · now</button></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div id=\"modal\"></div><script src=\"https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js\" crossorigin=\"anonymous\"></script><script src=\"/static/js/hotkeys.js?v=5\"></script><script>\n\t\t\t(function(){\n\t\t\t\tvar app=document.querySelector('.app');\n\t\t\t\t['sidebar','list'].forEach(function(p){\n\t\t\t\t\tif(localStorage.getItem(p+'-collapsed')==='1')app.classList.add(p+'-collapsed');\n\t\t\t\t});\n\t\t\t})();\n\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
